name: Build CLI & WASM

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build CLI (native)
        run: |
          go build -o homevision_unpacker .

      - name: Build WASM
        run: |
          cd cli
          GOOS=js GOARCH=wasm go build \
            -o ../frontend/main.wasm \
            main.go  # SOLO este archivo, NO parser.go

      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: builds
          path: |
            homevision_unpacker
            frontend/main.wasm
